//=========================================================
// src/rf392_EFMV02_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8SB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
//
// $[Generated Includes]
#include "cslib_config.h"
#include "cslib.h"
// [Generated Includes]$

#include "USER_PROGRAM.h"
#include "hgsemi74hc.h"
#include "board_efm8sb.h"

bit clib_keypressflag = 0;
extern unsigned char xdata STANDBY_TIME;
extern unsigned int xdata app_sleep_counter;

unsigned int xdata dlt_counter = 0;
unsigned int xdata dlt_counter1 = 0;
int xdata dlt_counter2 = 0;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
// $[SiLabs Startup]
  /*
   // WDTE (Watchdog Timer Enable) = DISABLED (Disable Watchdog Timer.)
   */
  PCA0MD &= ~PCA0MD_WDTE__BMASK;

// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  P2MDOUT |= 0x80;
  P2_B7 = 1;
  TMR2CN0_TR2 = 1;
  USER_PROGRAM_INITIAL ();
  TMR2CN0_TR2 = 0;
  //LEDALL_OFF();
  while (1)
    {

// $[Generated Run-time code]
      // -----------------------------------------------------------------------------
      // If low power features are enabled, this will either put the device into a low
      // power state until it is time to take another scan, or put the device into a
      // low-power sleep mode if no touches are active
      // -----------------------------------------------------------------------------
      CSLIB_lowPowerUpdate ();

      // -----------------------------------------------------------------------------
      // Performs all scanning and data structure updates
      // -----------------------------------------------------------------------------
      CSLIB_update ();

// [Generated Run-time code]$
      //INDICADE_PIN = !INDICADE_PIN;
      user_timer_process ();
      TMR2CN0_TR2 = 1;
      if (CSLIB_anySensorDebounceActive ())
        {
          clib_keypressflag = 1;
          app_sleep_counter = 0;
          //INDICADE_PIN = 0;
        }
      else
        {
          //INDICADE_PIN = 1;//key press timer define
          clib_keypressflag = 0;
          app_sleep_counter++;
        }

      USER_PROGRAM ();
      TMR2CN0_TR2 = 0;
      TMR2CN0_TF2H = 0;
      //TMR2H = 0xBC;//--16
      //TMR2L = 0x6A;
      TMR2H = 0xD8;//--8
      TMR2L = 0x20;
      //dlt_counter = (TMR2H << 8) + TMR2L;

      //LED7TURNON();
    }
}
