//=============================================================================
// inc/config/cslib_sensor_descriptors.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document. leave the sections
// inside the "$[...]" comment tags alone or they will be overwritten!
//=============================================================================

#ifndef __SILICON_LABS_CSLIB_SENSOR_DESCRIPTORS_H
#define __SILICON_LABS_CSLIB_SENSOR_DESCRIPTORS_H

void
outputsensorDescriptors (void);

#define HAS_SENSOR_DESCRIPTORS

// $[sensor descriptors]
#define SENSOR_DESCRIPTOR_LIST \
  "CS0.1", \
  "CS0.0", \
  "CS0.2", \
  "CS0.3", \
  "CS0.7", \
  "CS1.0", \
  "CS1.1", \
// [sensor descriptors]$

#endif // __SILICON_LABS_CSLIB_SENSOR_DESCRIPTORS_H

